name: ReactJS.NET
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
paginate: 5
paginate_path: /blog/page:num.html
url: https://reactjs.net
doc-sections:
 - id: getting-started
   title: Getting Started
 - id: guides
   title: Guides
 - id: dev
   title: Development
assets:
 css_compressor: sass
