name: ReactJS.NET
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
paginate: 5
paginate_path: /blog/page:num.html
url: https://reactjs.net
doc-sections:
    - id: getting-started
      title: 'Getting Started'
    - id: tutorials
      title: Tutorials
    - id: features
      title: Features
    - id: bundling
      title: Bundling
    - id: dev
      title: Development

title: Development
assets:
    css_compressor: sass
